PlatformIconStyle: 3
mapDefaultZoomLevel: 3
MaxTimeTillUnderIceFlag: 8
sidebarListFontSize: 14
HideBlockingPopupForClickedViews: false
useDMSFormatForTimestamps: true
DisplayCoordsOnOneLine: true
MaxCoordDecimals: 4
