enableDebug: false
DebugFS: true
DebugCalc: true
DebugInput: true
DebugState: true
DebugQueues: true
DebugView: true
DebugMap: true
DebugPlot: true
onlyLogSeriousNotifications: false
DebugELECTRON: true
