HideQCVarsForAxisDropdown: true
HideDMVarsForAxisDropdown: true
HideERRORVarsForAxisDropdown: true
HideVarsUnbalancedPopup: false
ensureYAxisIsAlwaysDisplaysDEPTH: false
IgnoreNoPresDataPopup: false
ensureYAxisAlwaysDisplaysDEPTH: false
